/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Negocio;

@Api(value = "negocio", description = "the negocio API")
@RequestMapping(value="/negocio")
public interface NegocioApi {

    @ApiOperation(value = "crear un negocio", nickname = "agregarNegocio", notes = "Agregar un negocio", tags={ "negociadores", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "negocio creado"),
        @ApiResponse(code = 400, message = "invalid input, object invalid"),
        @ApiResponse(code = 409, message = "negocio ya existe") })
    @RequestMapping(value = "/{idNegocio}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> agregarNegocio(@ApiParam(value = "ID de negocio a buscar",required=true) @PathVariable("idNegocio") String idNegocio,@ApiParam(value = "negocio a agregar"  )  @Valid @RequestBody Negocio negocio);


    @ApiOperation(value = "buscar un negocio", nickname = "buscarNegocio", notes = "Enviando un ID valido devuelve la informacion del negocio ", response = Negocio.class, tags={ "administradores","negociadores", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "devolver resultado obtenido", response = Negocio.class),
        @ApiResponse(code = 400, message = "parametro incorrecto") })
    @RequestMapping(value = "/{idNegocio}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Negocio> buscarNegocio(@ApiParam(value = "ID del negocio a buscar",required=true) @PathVariable("idNegocio") String idNegocio);

}
