/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.TipoInmueble;

@Api(value = "tipoInmueble", description = "the tipoInmueble API")
@RequestMapping(value = "/tipoInmueble")
public interface TipoInmuebleApi {

    @ApiOperation(value = "crear un tipo de inmueble", nickname = "agregarTipoInmueble", notes = "Agregar un tipo de imueble", tags={ "administradores", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "tipo inmueble creado"),
        @ApiResponse(code = 400, message = "invalid input, object invalid"),
        @ApiResponse(code = 409, message = "tipo nmueble ya existe") })
    @RequestMapping(value = "/{idTipoInmueble}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> agregarTipoInmueble(@ApiParam(value = "ID del tipo de inmueble a buscar",required=true) @PathVariable("idTipoInmueble") String idTipoInmueble,@ApiParam(value = "tipo inmueble a agregar"  )  @Valid @RequestBody TipoInmueble tipoInmueble);


    @ApiOperation(value = "buscar un topo de bien raiz", nickname = "buscarTipoInmueble", notes = "Enviando un ID valido devuelve la informacion del tipo de inmueble ", response = TipoInmueble.class, tags={ "administradores","negociadores", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "devolver resultado obtenido", response = TipoInmueble.class),
        @ApiResponse(code = 400, message = "parametro incorrecto") })
    @RequestMapping(value = "/{idTipoInmueble}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<TipoInmueble> buscarTipoInmueble(@ApiParam(value = "ID del tipo de inmueble a buscar",required=true) @PathVariable("idTipoInmueble") String idTipoInmueble);

}
