version: "3"

services:
  mysql:
    image: mysql:5.6
    command: mysqld --max-connections=1000 --max-allowed-packet=32M --innodb-log-file-size=256M --lower-case-table-names=1
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    
    volumes:
       - ./inmueble-mysql/data:/var/lib/mysql/data

  inmueble:
    container_name: inmueble
    build:
      context: .
    image: inmueble:latest
    expose: 8080
    depends_on:
      - mysql
    environment:
      - MYSQL_INSTANCE=mysql:3306
    ports:
      - "8080:8080/udp"
    networks:
      - network1

networks:
  network1:
